### ISSUE TITLE
(Windows) No portable option

### ISSUE THREAD

**Issue by Baddest-Juju** [ugetdm/uget-integrator#1]
uGet is a portable app, which I like. This really flies in the face of that. I don't want to install anything, I want something that can be transported between OSes easily.

Please offer a way to get this working without having to install the wrapper. Something like uGet's "Path Register.exe" would be nice.

**Comment by slgobinath** [comment]
A configuration file is added for portable installation (aka extraction). (See https://github.com/ugetdm/uget-integrator/commit/d59e5745de98534b8817a376d66bfce0fbd4389e)

Please have a look at the installation method (https://github.com/ugetdm/uget-integrator#portable-method) and share your feedback. Still, required files are not there. So just go through the instructions and see whether it makes sense.

**Comment by slgobinath** [comment]
Fixed
