### ISSUE TITLE
uGet Integration 2.1.2 icon turn red in Chrome-Windows 7

### ISSUE THREAD

**Issue by syahrpn** [ugetdm/uget-integrator#10]
After upgrading to "uGet Integration 2.1.2", It looks like python 3.6.4 doesn't support my machine/os. I'm using Windows 7 Ultimate SP1. I'd already modified the "uget-integrator.bat" file in the "uget-integrator" folder and then installed the Python 3.4 in it. And now the uGet Integration icon at the upper right corner in  chrome is finally turned green.

**Comment by slgobinath** [comment]
Hi,
Could you please share more insights with us?
1. How did you install uget-chrome-wrapper (Manual/Installer)?
2. Could you please try to open `python-3.6.4\python.exe` from the command line and see whether it works?

Thanks

**Comment by syahrpn** [comment]
@slgobinath Hi,
1) I'm using the installer version
2) No. I captured the window as attached image
![capture 1](https://user-images.githubusercontent.com/37666505/37783351-402cf488-2e30-11e8-988a-7bee589800e1.PNG)

**Comment by slgobinath** [comment]
Got it. Problem is I packaged Python 64 bit.
I will change it to 32 bit.

Thanks

**Comment by slgobinath** [comment]
Hi,
I have replaced the installer and zip file with 32bit Python. Could you please uninstall your existing uget-integrator and install the new one and let me know the results?

Thanks

**Comment by syahrpn** [comment]
It's done..I already installed the new one and now it works..Thanks a lot..

**Comment by Xz1c0** [comment]
hi i have same problem in win 8.1 pro 64 bits  firefoxe 32bits python 3.6.4 32 bits help me pls

**Comment by slgobinath** [comment]
Hi,
Couldn't you able to run `python-3.6.4\python.exe` from the command line? I have a testing VM with Windows 10 64 bit and able to run Python 32bit. We also had problems with Firefox 32 bit on a 64bit operating system.

Please try to run Python manually and let me know.

Thanks

**Comment by Xz1c0** [comment]
@slgobinath hi
i captured the windows 

![run](https://user-images.githubusercontent.com/37693131/37831012-572efd06-2ea4-11e8-86ff-9338ec174ee7.JPG)
and firefoxe plugin
![plugin](https://user-images.githubusercontent.com/37693131/37831202-ef8be7bc-2ea4-11e8-8b6b-60b30e098e62.JPG)

**Comment by slgobinath** [comment]
Hi,
Python is working properly.
>  **win 8.1 pro 64 bits firefox 32bits** python 3.6.4 32 bits

Firefox architecture should match with Windows architecture. Please download and install Firefox 64bit from https://download.mozilla.org/?product=firefox-latest-ssl&os=win64&lang=en-US

Please check https://github.com/ugetdm/uget-integrator/wiki/Known-Issues#firefox-not-interrupting-downloads

**Comment by Xz1c0** [comment]
Hi @slgobinath
same problem  in Firefox 64 bit but its working in chrome 64 bit perfectly 

1. Firefox
![firefox](https://user-images.githubusercontent.com/37693131/37842702-1c9a0720-2ec3-11e8-9a8e-d40cb00a5481.JPG)

2. Chrome 
![uget work perfect in chrome](https://user-images.githubusercontent.com/37693131/37842722-2dcd49d0-2ec3-11e8-9baa-1838ef5b28e4.JPG)

thank you  so much

**Comment by nesta12** [comment]
Hey,
i have the same issue here, and i couldn't figure out a solution although it used to work perfectly before.
i'm using firefox and linux mint 18.3

**Comment by slgobinath** [comment]
I am closing this issue since it was related to Python architecture and fixed already.

Let's discuss the issue in Firefox at https://github.com/ugetdm/uget-integrator/issues/16.
