### ISSUE TITLE
uget-integrator for freebsd

### ISSUE THREAD

**Issue by hadipeyro** [ugetdm/uget-integrator#100]
Hi good time
Is there a way to install uget-integrator on freebsd?
I've been using uget-integrator on GNU/Linux but now I need it on freebsd. This tool is really important for me. I'll be really appreciate if you help me.
Thanks.

**Comment by ghost** [comment]
Doubtful as uget-integrator isn't really updated anymore..
Try Persepolis or any other alternative for BSD.

**Comment by knaggsy2000** [comment]
@django-nauts @ghost Wrong.  #117.

I've just done this.
