### ISSUE TITLE
Ubuntu 20.10: Unable to locate uget-integrator

### ISSUE THREAD

**Issue by amwambu** [ugetdm/uget-integrator#101]
Hello,
on ubuntu 20.10, when I use the following commands in the terminal:

```
sudo add-apt-repository ppa:uget-team/ppa
sudo apt update
sudo apt install uget-integrator
```

but, it outputs:

`E: Unable to locate package uget-integrator`

How do I solve this?
thanks.

**Comment by MichaelTunnell** [comment]
Unfortunately, it seems that uget-integrator has not been built for 20.10 and is only available for 20.04 and older at the moment.
