### ISSUE TITLE
Firefox extension unable to connect with uget-integrator

### ISSUE THREAD

**Issue by indirected** [ugetdm/uget-integrator#103]
Hi. I have been using uget with firefox with no problem with ubuntu 20.04. recently i upgraded to 21.10 and i have updated my uget ppa.
currently i have uget and uget-integrator. both of them are accessible through terminal and this my `apt list uget*`
```
uget-integrator/impish,now 1.0.0-1 amd64 [installed]
uget-integrator/impish 1.0.0-1 i386
uget/impish,now 2.2.3-2 amd64 [installed]
```
but the firefox extension keeps giving me "unable to connect with uget-integrator".
I also tried uninstalling reinstalling the extension, purging with `apt purge uget*` and installing everything again and restarting my computer.
non of them seem to work. any suggestions?

**Comment by MrTazocin** [comment]
I can normally use here. Try update the PPA repo cache and install again

**Comment by slgobinath** [comment]
@indirected is your Firefox upgraded to the Snap version?

**Comment by reckerswartz** [comment]
Same issue with me.

![image](https://user-images.githubusercontent.com/16918568/143032085-3fc8f956-6510-4331-a51d-1ad568e062c9.png)
![image](https://user-images.githubusercontent.com/16918568/143032455-ba4e2162-5643-4090-b9d7-96154bae6ac9.png)
![image](https://user-images.githubusercontent.com/16918568/143032539-e453c974-57cc-4d0f-bfc0-37b74d0d0c42.png)

**Comment by slgobinath** [comment]
Can you try uninstalling the currently installed Firefox and try the following command to install it again:
```
sudo apt install firefox
```

According to https://www.omgubuntu.co.uk/2021/09/ubuntu-makes-firefox-snap-default Ubuntu 21.10 ships Firefox Snap package which may not connect to the uget-integrator.

**Comment by reckerswartz** [comment]
worked! 
but not everyone going to make such a switch.

**Comment by slgobinath** [comment]
@reckerswartz yeah I agree with you but I don't think there's a solution right now.

Even the Gnome Extension to install extension from the website doesn't work with snap package.

**Comment by indirected** [comment]
I have switched to apt packages firefox and can confirm the problem is with the snap packages firefox.
Also, snap firefox is pretty slow. I suggest anyone who's reading this switch back to apt.
thanks for the answers btw.
