### ISSUE TITLE
Minimum file size option does not work

### ISSUE THREAD

**Issue by teonas35** [ugetdm/uget-integrator#11]
Minimum file size option does not work on chromium in my arch linux installation. I removed old wrapper and installed the new one and my system fully updated. I tried several file sizes (in kb) and downloaded the files and every time i tried uget interrupted the download process. This option was working on previous version.

**Comment by slgobinath** [comment]
Fixed with https://github.com/ugetdm/uget-extension/commit/4103443c988fc022fbb2ad46784b00d3cacfb76c. Will be included in the next extension release.

**Comment by slgobinath** [comment]
Fix included in the new version 2.1.3
