### ISSUE TITLE
No uget intgrator for opera linux....

### ISSUE THREAD

**Issue by psposito** [ugetdm/uget-integrator#14]
Hello,

Unfortunately Opera for linux is missing the new extension....

**Comment by slgobinath** [comment]
Hi,
I have already submitted the extension for Opera but Opera developers take more time to validate.

Please leave this issue open until Opera publishes the extension.

**Comment by slgobinath** [comment]
Hi,
If you like to install Opera add-on manually (until they publish it), please download the `uget-integration-chrome.zip` from [releases](https://github.com/ugetdm/uget-extension/releases) and drag and drop in Opera extensions.

**Comment by candrapersada** [comment]
or use
https://addons.opera.com/en/extensions/details/install-chrome-extensions/
and
https://chrome.google.com/webstore/detail/uget-integration/efjgjleilhflffpbnkaofpmdnajdpepi
