### ISSUE TITLE
No Need to Install Python

### ISSUE THREAD

**Issue by sharat1990** [ugetdm/uget-integrator#17]
I uninstalled the list of S/W's on (Windows 10):
1)Python
2)UGet
3)UGet Chrome Wrapper
4)UGet Chrome Extension

Then I have installed these S/W's without installing Python and it works for me.
UGet Windows Installer
Uget Integrater
UGet Chrome Extension

Is it mandatory to install Python ? but It works for me with out installing Python.

**Comment by slgobinath** [comment]
Python is no longer required :-)
uget-integrator comes with embedded Python 3.6.4 (you can see this in the installation folder)
