### ISSUE TITLE
uget opera extension looking for uget-chrome-wrapper

### ISSUE THREAD

**Issue by fahadakbar24** [ugetdm/uget-integrator#19]
Browser: opera(52.0.2871.40)
OS: Ubuntu 17.10 (x86_64; ubuntu:GNOME)

Extension version: 2.1.1.1
uget-integrator version: 1.0.0-1

![screenshot from 2018-04-02 11-00-42](https://user-images.githubusercontent.com/26380184/38186168-fe8f3660-366a-11e8-95c9-9c5aee65f255.png)

**Comment by candrapersada** [comment]
use
https://addons.opera.com/en/extensions/details/install-chrome-extensions/
and
https://chrome.google.com/webstore/detail/uget-integration/efjgjleilhflffpbnkaofpmdnajdpepi

**Comment by fahadakbar24** [comment]
Worked, Thanks :)

**Comment by candrapersada** [comment]
share for users opera other

**Comment by glaubersm** [comment]
Hi
I use uget 2.2.1 on Arch Linux running Gnome 3.28.2 and Opera 54.0.2952.46.

I have uget integration 2.1.3 from chrome web store, uget integration 2.1.1 from opera addons website, uget integration 1.0.0-1 from AUR repository installed and browser integration is not working.

uget integration 2.1.3 says "unable to connect with "uget-integrator".
uget integration 2.1.1 says "error: unable to connect to the "uget-chrome-wrapper"

**Comment by slgobinath** [comment]
Opera developers take forever to review the latest release. So I gave up it and recommend users to install the Chrome extension using https://addons.opera.com/en/extensions/details/install-chrome-extensions/

**Comment by glaubersm** [comment]
it works with uget integration 2.1.3 extension from chrome web store.
Thanks.

**Comment by slgobinath** [comment]
After waiting for more than 3 months, finally, opera add-on has been reviewed and published by Opera developers on July 12th.
Now you can install Opera extensions from https://addons.opera.com/en/extensions/details/uget-integration/

![waiting_for_review](https://user-images.githubusercontent.com/4003168/42888992-6358558a-8a77-11e8-8ed7-2bd25aec7e01.jpg)

**Comment by joelebukatobi** [comment]
Mine is not working I'm on Ubuntu18.04 Using Chrome and the uget integration version is 2.1.3
