### ISSUE TITLE
(Windows) Compatibility with Python embeddable zip file

### ISSUE THREAD

**Issue by Baddest-Juju** [ugetdm/uget-integrator#2]
Instead of having the user install python and then copy the python directory into the bin folder, why not just have the user download the embeddable zip file, available from here for instance: https://www.python.org/downloads/release/python-364/

Could be extracted or you could have an executable that can use the embed.

**Comment by slgobinath** [comment]
> Instead of having the user install python and then copy the python directory into the bin folder

I don't get this. Users must install Python which will add `py` to PATH.

**Comment by DanaMW** [comment]
I think he is mistaken all he needs to do is install python, it adds  itself to the PATH if you let it and he should. 
Install  uget add uget/bin to PATH (Either installer or portable)
install uget wrapper add the exact uget-wrapper folder to the PATH
then install python and let it add itself to the path. Reboot and your done,

**Comment by Baddest-Juju** [comment]
It's on their official website: https://slgobinath.github.io/uget-chrome-wrapper/

1. Install Python 3.4 or latest
2. Download and extract uGet to C:\uget folder
3. Add the Python installation directory and C:\uget\bin folder to the environment variable PATH
4. Download and install the latest uget-chrome-wrapper_x.x.x.x.exe
5. Restart the computer

2. Install the uGet Integration extension in your browser
* Google Chrome, Chromium & Vivaldi users: Chrome Extension
* Opera users: Opera Extension
* Mozilla Firefox 56+ users: Firefox Addon

There's new instructions on this github but no new builds out for it.

**Comment by DanaMW** [comment]
The wrapper on old website (2.0.7) still works and installs and runs perfect. Just did a windows machine last night.
https://github.com/slgobinath/uget-chrome-wrapper/releases/download/v2.0.7/uget-chrome-wrapper_2.0.7.0.exe

**Comment by Baddest-Juju** [comment]
>installs

That's the issue. I want to use uGet as it was originally intended - portable. It even has batch files for adding the necessary Uri handlers.

**Comment by DanaMW** [comment]
What your asking for i believe then is a portable version of the wrapper?? Because none of the other programs stops uget from being portable, i use that one myself.  Maybe i am closer to the mark?

**Comment by Baddest-Juju** [comment]
Yes, I opened issue #1 because I wanted to see a portable version.

However I wouldn't want the portable version to have to rely on copying a Python installation, so I opened this issue separately. I think using the embeddable version of Python would be ideal.

**Comment by DanaMW** [comment]
Understood. Ok lol just thought i was helping, I'll climb back in my hole now.

**Comment by Baddest-Juju** [comment]
Sorry if I seemed rude, it was not my intention.

**Comment by DanaMW** [comment]
We are fine, you just seemed exasperated and I was trying to help.  And I was and am glad to do that. I just misunderstood.

**Comment by slgobinath** [comment]
Thanks for giving me this idea.
Now Python is embedded in the installer (See https://github.com/ugetdm/uget-integrator/commit/795e3bca8b7b304d97c8d93fe7433b0e9258f023). I will include it in the portable version too.

**Comment by DanaMW** [comment]
you are the man :) if you only knew how much I use this add-on lol

**Comment by Baddest-Juju** [comment]
I'm a little confused. When I click on the link to download 'uget-integrator-portable_x.x.x.x.zip' it brings me to a page that says 'There aren’t any releases here'.

**Comment by slgobinath** [comment]
Hi,
Still, uget-integrator is under testing so I have not released it yet. However, I wanted to ensure that the expected installation procedure meets your requirement.
I have added a new [remove_config.bat](https://github.com/ugetdm/uget-integrator/blob/master/install/windows/remove_config.bat) file to remove configurations.

> Could you please make this support relative pathing?

It depends on how browser executes native-messaging-host. I will test relative path and update the document.

**Comment by Baddest-Juju** [comment]
If relative pathing for UGET_COMMAND doesn't work out, then it is possible that config.bat could supply the proper path in its stead.

Let me know how the tests go and if they don't work out I'll whip something up.

**Comment by Baddest-Juju** [comment]
Any luck?

**Comment by slgobinath** [comment]
Found an alternative using script path feature in Python. Guaranteed to work however I will commit it after testing in my VM.

**Comment by slgobinath** [comment]
Hi,
The portable method instruction is updated for the relative path. Providing relative path itself worked for me. However, I am afraid to use it because it highly depends on the behavior of the browser. Therefore, I recommend the following format:
```
UGET_COMMAND = join(os.path.dirname(os.path.realpath(__file__)), "..\\uget\\bin\\uget.exe")
```

If you find anything to improve, please do let me know.

> NOTE: Still I haven't release uget-integrator. So you cannot actually test the instructions.

**Comment by slgobinath** [comment]
Hi,
If I provide a pre-release, will you be able to test and provide your feedback?

**Comment by Baddest-Juju** [comment]
> @slgobinath If I provide a pre-release, will you be able to test and provide your feedback?

Yup, sure will. Haven't really found a download manager solution I'm happy with thus far, I think the changes you've made will make this the thing to use.

**Comment by slgobinath** [comment]
Thanks.
Please follow these steps to test with Chrome, Chromium, Vivaldi and Opera
1. Please download `uget-integrator-0.0.1` and setup with uGet 2.2.0.
2. Download [uget-extension](https://github.com/ugetdm/uget-extension/archive/master.zip) from GitHub
3. Replace [extension/manifest.json](https://github.com/ugetdm/uget-extension/blob/master/extension/manifest.json) by the attached manifest.json (Extract the attached [manifest.json.zip](https://github.com/ugetdm/uget-integrator/files/1720950/manifest.json.zip) file)
4. Open `chrome://extensions/` in Chrome (extension manager in your browser)
5. Enable `Developer Mode`

6. Click on `Load unpacked extension` button and select the `uget-extension
/extension` folder.

**Comment by Baddest-Juju** [comment]
@slgobinath Yeah, I've done unofficial extensions before. I've now got it running on both Chromium (with the manifest from the zip file) and Firefox (with the original manifest).

What next?

**Comment by slgobinath** [comment]
Is it running as expected?
Could you please test the following features:
1. Interrupting a download
2. Downloading Youtube videos
3. Enable/Disable and other options available through the extension dialog

**Comment by Baddest-Juju** [comment]
@slgobinath Er... the extension is just one piece of the pie here though? I don't believe you've released the python integrator (the one that uses an embeddable Python 3.6.4 library) anywhere.

Is testing the old integrator that uses Python 3.4 really going to be useful?

**Comment by slgobinath** [comment]
The pre-release I said was the one with embedded Python 3.6.4.
Please check https://github.com/ugetdm/uget-integrator/releases

The new extension (which I shared) does not support the previous uget-chrome-wrapper.

**Comment by Baddest-Juju** [comment]
Ahh, I see, I'm a bit distracted and I inadvertently skipped step 1. One moment.

**Comment by Baddest-Juju** [comment]
Oh, I should mention I tested on both Firefox and Chromium, everything is working as intended on both.

**Comment by slgobinath** [comment]
Thank you very much for your feedback and fix.

> To fix this, add this right below @echo off in your batch files

Fixed in https://github.com/ugetdm/uget-integrator/commit/69ce827b158b91ff77e17f458caba58fdc4e49a9.

uGet is no longer required to run beforehand after the fix in https://github.com/ugetdm/uget-integrator/commit/3cf291e7b353a060d79d725b276f607058274a4d by @AirQuick.

> why not just package the integrator in with uGet?

It was not preferred because of the Python dependency and to avoid dependency between uGet release and uGet-Integrator release. uget-integrator may require frequent releases as it is not matured yet. Therefore packaging them together will either slow down release cycle or increase version number without new features in uGet download manager.

@MichaelTunnell please share your point of view.

**Comment by Baddest-Juju** [comment]
Well, you could have uGet auto-update separately.

I do notice that you packaged the entire Python library in. Was the typical embeddable redistributable not enough?

**Comment by Baddest-Juju** [comment]
for reference, this is the embeddable zip file.

https://www.python.org/ftp/python/3.6.4/python-3.6.4-embed-amd64.zip

I notice a lot of Windows binaries that use python just plop this in the folder, keeping it in its nice little zip container. Not entirely sure how it works, though I do know a project that does that. I could look up the code if need be.

**Comment by slgobinath** [comment]
Since the decision was initially made by Michael and C.H, I leave it to him.

**Comment by Baddest-Juju** [comment]
In the meantime.. might I suggest you assign a default value to line 38? I personally went with this:

```
UGET_COMMAND = join(os.path.dirname(os.path.realpath(__file__)), "..\\bin\\uget.exe")
```

It's close to your suggestion, but it just allowed me to plop the 'uget-integrator' folder directly into the uget folder, and because of the alphabetical sorting it's the bottom-most folder, so that works out nicely.
