### ISSUE TITLE
[Browser Extension] Version 2.1.3 Doesn't interrupt anything anymore. 

### ISSUE THREAD

**Issue by Gristrosia** [ugetdm/uget-integrator#20]
Hi,

I use Firefox with Uget Integrator and Uget portable, and since yesterday's update (v2.1.3), the Uget Integration browser extension doesn't interrupt anything anymore.

**Comment by slgobinath** [comment]
Hi,
Firefox reports files size `-1` to all downloads (which I have added in none issues section). To overcome this issue, please set `-1` as the minimum file size to interrupt.

**Comment by slgobinath** [comment]
I found a solution for this problem. I will release the fix today.

**Comment by slgobinath** [comment]
Fixed in 2.1.3.1 which is now available on Firefox website
