### ISSUE TITLE
Just an update on handlers.json

### ISSUE THREAD

**Issue by DanaMW** [ugetdm/uget-integrator#3]
My original suggestion of deleting handlers.json is or was good but I seemed to have to re-delete every so often so I decided to work up another solution. I loaded handlers.json in notepad++ and used the add-on json formatter to format it readable then i added the mime types to it myself. It always seems that *.exe files went to the browser no matter what i did so I added: 
		"application/exe": {
			"action": 0,
			"ask": false,
			"extensions": ["exe"]
		},
		"application/octet-stream": {
			"action": 0,
			"ask": false,
			"extensions": ["exe"]
	       }
Now it grabs and sends them fine I added like mp3 and mp4 zip pdf  and others I download to it too. Working perfectly  now.
as for what the action are... and zero is what you would want i  believe.
0 = Save To Disk
1 = Always Ask
2 = Use Helper App
3 = Handle Internally
4 = Use System Default

Hope this might help someone else. Oh and here is a listing of the mimetypes if you need them,
[MimeTypes.pdf](https://github.com/ugetdm/uget-integrator/files/1686634/MimeTypes.pdf)

**Comment by slgobinath** [comment]
Thanks for updating me.
I have included this issue in README known issues section (https://github.com/ugetdm/uget-integrator/commit/dc2a84498a9a0512de88593aa6772a8421ac7df4)

**Comment by Schattenjager-RC** [comment]
I used Firefox extension Content-Type Fixer to solve this problem.
https://addons.mozilla.org/ru/firefox/addon/content-type-fixer/
