### ISSUE TITLE
File downloading doesn't start automatically in Firefox 61.0

### ISSUE THREAD

**Issue by AndroVGG** [ugetdm/uget-integrator#41]
I'm using Firefox 61.0 (x64) with uGet 2.2.1 on Windows 7 x64. uGet Integration is set correctly and shows the message: "Found uget and uget-integrator". But uGet doesn't start file downloading automatically after clicking a link. The only way to initiate the process is manually from the context menu (if the link is direct). Is there any way to fix it?

**Comment by slgobinath** [comment]
How did you install uget-integrator?

In Windows, there was a known issue which was fixed in a later version. Could you please start uGet first and then try to download a file. If it is not working, please share the file you tried to download.

**Comment by AndroVGG** [comment]
@slgobinath
> How did you install uget-integrator?

**1.** I installed "uget-integrator_1.0.0.1.exe"
**2.** In "uget-integrator.py" I set the absolute path of "uget.exe" in line 38: `UGET_COMMAND = "C:\\Program Files (x86)\\uGet\\bin\\uget.exe"`
**3.** I executed "add_config.bat"

> Could you please start uGet first and then try to download a file.

Nothing's changed.

> If it is not working, please share the file you tried to download.

That's true for any file. Even for [https://github.com/ugetdm/uget-integrator/releases/download/v1.0.0/uget-integrator_1.0.0.1.exe](https://github.com/ugetdm/uget-integrator/releases/download/v1.0.0/uget-integrator_1.0.0.1.exe).

**Comment by glaubersm** [comment]
Situation is exactly the same on my system.
I use uget 2.2.1 on Arch Linux running Gnome 3.28.2 and Firefox 61.
Both uget-integrator 1.0.0-2 and uget-integrator-firefox 1.0.0-1 installed from AUR repository and  uget integration addon 2.1.3.1 installed from Firefox addons website.

**Comment by slgobinath** [comment]
Could you please you set `application, video, audio` to the first `Always Interrupt` box in the extension settings dialog and check the https://github.com/ugetdm/uget-integrator/releases/download/v1.0.0/uget-integrator_1.0.0.1.exe again?

**Comment by AndroVGG** [comment]
@slgobinath 
Now it works perfectly. Thanks for your help.
