### ISSUE TITLE
Download Star

### ISSUE THREAD

**Issue by Baddest-Juju** [ugetdm/uget-integrator#5]
Disclaimer: I'm not suggesting you make this compatible.

There is an incompatible extension for Firefox known as Download Star. It offers functionality that no other Quantum extension currently does, letting you start downloads based on a pattern. There's two problems. 1) It isn't being maintained, the last update being 5 months ago. 2) It's incompatible with the uget extension.

Would it be possible for you to examine this functionality and then add your own version for the uGet extension?

**Comment by slgobinath** [comment]
Hi,
Similar functionality is already there. If you select `Download all links with uGet` from right-click context menu, uGet will show a dialog to filter the links. Currently, this filter checks only hosts and extensions.
I think it is better to improve the existing filter to match advanced patters than duplicating similar feature within the add-on.

@MichaelTunnell WDYT?

**Comment by Baddest-Juju** [comment]
Not quite. Download 'Download Star' and click on it while on a page. It's not just about downloading stuff you highlight, in fact it's not that at all. You can set it to download all jpgs, all txts, etc. no matter where they are.

**Comment by slgobinath** [comment]
> no matter where they are.

Does it mean that downloads from all tabs? If it is from the current tab, that is available in uGet too.

To download all urls from a page, do not right click **on** a link. Instead right click on the page (a blank region or something that is not a link/media), you will get an option `Download all links with uGet`.

**Comment by Baddest-Juju** [comment]
Well how about that. I had no idea you could do that. Thank you.
