### ISSUE TITLE
Several 404 page not found

### ISSUE THREAD

**Issue by Neustradamus** [ugetdm/uget-integrator#63]
- https://ugetdm.com/versioncheck?v=x.x.x
- https://ugetdm.com/documentation
- https://ugetdm.com/feedback
- https://ugetdm.com/reportbug
- https://ugetdm.com/keyboard-shortcuts
-> 404 

"Page not found"

"Nothing Found"

"It seems we can’t find what you’re looking for. Perhaps searching can help."

"Search for:"

**Comment by MichaelTunnell** [comment]
thank you for the report however this is not related to uget-integrator.

Bug Reports for uGet are to be made here: https://ugetdm.com/qa/bug-reports

I do need to fix these though thats true.
