### ISSUE TITLE
Double left click on the file selection does not open it

### ISSUE THREAD

**Issue by Neustradamus** [ugetdm/uget-integrator#64]
Double left click on the file selection does not open it

We must to right click -> open or enter button on the file selection.

**Comment by MichaelTunnell** [comment]
Not related to uget-integrator.

Feature Requests to uGet are to be made here: https://ugetdm.com/qa/feature-requests

**Comment by Neustradamus** [comment]
Yes all my tickets are for uGet :)
You will not closed all tickets?
Have you an email for contact team?
Because I have not account on this website, Github is a best plateform for devs.

**Comment by MichaelTunnell** [comment]
this repo is for uget-integrator so issues must be for uget-integrator.

I only close tickets not related to uget-integrator as that is what this repo is for.

we do not have a email for the whole team no

>"Because I have not account on this website"

It's our website so it would be shocking for you to have an account before knowing about it. However, this is where we want people to submit this info.

GitHub is in your opinion the best however some people don't think so for a variety of reasons. I am willing to make a repo for it here just for issues to make it easier for users though. That's doable.

Edit: https://github.com/ugetdm/uget (of course don't expect me to be as attentive on that repo as I am for the uGet QA system)

**Comment by Neustradamus** [comment]
@MichaelTunnell Thanks for this change!
It is possible to move SF to Github?
Or a mirror...

**Comment by MichaelTunnell** [comment]
No, we have no reason to move from SF to GitHub. I will look into a mirror though.
