### ISSUE TITLE
Which uGet version is required?

### ISSUE THREAD

**Issue by z1atk0** [ugetdm/uget-integrator#66]
Just curious, is this supposed to work with uGet 1.10 as well, or do I need to upgrade to uGet 2.x? Thanks! :-)

**Comment by MichaelTunnell** [comment]
uGet 2.2.1 is the latest version, uGet 2.2.0 is a minimum requirement for support with our continued development.

uGet 1.10.x was deprecated 4 years ago. We do not support it or develop any features for it including this extension.
