### ISSUE TITLE
Firefox doesn't download the addon from addon page.

### ISSUE THREAD

**Issue by KataStrofY** [ugetdm/uget-integrator#71]
Firefox (66.0.3) does not want to install the add-on. When clicking on "Add to Firefox" from the add-on page, I get the error "Download failed. Please check your connection.". Trying to open the link in a different tab, I get a message that the addon might be corrupt.

I have tried installing a few different addons, and none of them are giving me the same errors.

**Comment by MichaelTunnell** [comment]
Firefox messed up their addon system yesterday, this is not a uget issue.
