### ISSUE TITLE
can't download...

### ISSUE THREAD

**Issue by y-ravishanka** [ugetdm/uget-integrator#75]
![Screenshot from 2019-08-15 09-48-07](https://user-images.githubusercontent.com/52966776/63072792-53229480-bf43-11e9-9d03-159b10c0b007.png)

**Comment by slgobinath** [comment]
Hi,
I tried on my machine and it's working. What is your firefox version?

**Comment by slgobinath** [comment]
Please check https://forums.linuxmint.com/viewtopic.php?t=297503

**Comment by y-ravishanka** [comment]
thank you....
now it's working.... it didn't before....
