### ISSUE TITLE
Extension searches for higher version

### ISSUE THREAD

**Issue by DanaMW** [ugetdm/uget-integrator#8]
The extension is looking for version 1.0.7. Just so you know. I installed the wrapper but it is only version 1.0.0 and is not found by the extension for some reason. Thanks for your work the wrapper goes in fine checking registry now.

**Comment by slgobinath** [comment]
Hi,
Required integrator version is: `1.0.0` (See https://github.com/ugetdm/uget-extension/blob/master/extension/background.js#L22) which should be equal to https://github.com/ugetdm/uget-integrator/blob/master/bin/uget-integrator#L39

**Comment by DanaMW** [comment]
do i have to uninstall and reinstall?  this is from my chrome extension:
var EXTENSION_VERSION = "2.1.1";
var REQUIRED_WRAPPER_VERSION = "2.0.7";
var interruptDownloads = true;
var ugetWrapperNotFound = true;

**Comment by DanaMW** [comment]
I am out of touch I guess is the new one replacing the old or is it listed as a new one?

**Comment by DanaMW** [comment]
Ok for some reason chrome is not updating properly

**Comment by DanaMW** [comment]
You can close this if you want, I just grabbed the master till your new extension is ready
Thank you  again

**Comment by slgobinath** [comment]
Hi,
Still I have not released the new extension. I am waiting for Arch package maintainer to update AUR. To use the latest uget-integrator, you need to install the extension from Github. I hope to release the extension within few days.

**Comment by DanaMW** [comment]
Cool thank you.

**Comment by slgobinath** [comment]
Hi,

New extension is released. You can install it from web stores.

**Comment by candrapersada** [comment]
extension opera slow?

**Comment by slgobinath** [comment]
Opera and Firefox manually verify submitted extensions. So it takes some time depending on availability of developers on their side.
This time Firefox add-on was verified immediately but Opera add-on is still waiting...

**Comment by candrapersada** [comment]
Install Chrome Extensions for opera?

**Comment by slgobinath** [comment]
You can but I hope it will be approved within few days (Usually 1-2 days)

**Comment by DanaMW** [comment]
Thank you by the way for all your work here. Seems to be ok but i am not sure the file size setting is reading but I dont use it i want it to catch them all.

**Comment by candrapersada** [comment]
![13929153431064372254](https://user-images.githubusercontent.com/36833664/37804399-a012a4e8-2e66-11e8-9849-c4e8bab02265.jpg)
version next.

**Comment by slgobinath** [comment]
Hi,
@DanaMW minimum file size issue has been fixed and will be included in the next release

@candrapersada it requires a significant amount of work. I will implement it once I get enough time.

**Comment by DanaMW** [comment]
I might wear my thank'er out today:) thank you @slgobinath
