### ISSUE TITLE
Can not install uget-inegrator on Pop OS 19.10

### ISSUE THREAD

**Issue by Ashutosh-Kukreti** [ugetdm/uget-integrator#83]
I'm getting the following error while adding the ppa to the repistory.

> E: The repository 'http://ppa.launchpad.net/uget-team/ppa/ubuntu eoan Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

![image](https://user-images.githubusercontent.com/38154154/70851686-4f395b80-1ebe-11ea-9a73-e14c5960374a.png)

**Comment by expatjedi** [comment]
Have you tried again? If you did you may want to close this issue.

**Comment by Ashutosh-Kukreti** [comment]
Thanks :)
