### ISSUE TITLE
Unable to locate package uget-integrator

### ISSUE THREAD

**Issue by atique7465** [ugetdm/uget-integrator#84]
hello, i am on ubuntu 19.10.  i used these commands on terminal:
```
sudo add-apt-repository ppa:uget-team/ppa
sudo apt update
sudo apt install uget-integrator
```
but, it ends with

`E: Unable to locate package uget-integrator`

could you please check this out.
thanks.

**Comment by expatjedi** [comment]
Package seems exist! I think they uploaded the file for your ubuntu version in same day so please try again. It should work now.
