### ISSUE TITLE
File names and extensions faulty when sent to uGet

### ISSUE THREAD

**Issue by brukberhane** [ugetdm/uget-integrator#88]
It seems that the file names of the downloads I start are different when sent to uGet. It either sends a seemingly random GUID or another name that would be seemingly unrelated. This error doesn't seem to be a problem with other tested download managers. Let me know if you would want screenshots or anything.

**Comment by OmarWKH** [comment]
This fixed it for me: https://aavtech.site/2019/08/workaround-for-uget-integration-wrong-file-name/

**Comment by brukberhane** [comment]
Thanks @OmarWKH. I'll try it and close the issue if it works for me

**Comment by brukberhane** [comment]
Yes, it worked very well. Thank you @OmarWKH!

**Comment by RedSnt** [comment]
Getting uGet to work on Windows has been quite the adventure, but having to dig through 3 issue trackers before finding this particular thread gave me a few grey hairs 😅 Thanks for the fix. Ironically I only really noticed this bug happening with Github downloads.  
Anyway, posting the guide here in case the link @OmarWKH posted goes down:

> ### Find uget-integrator.py file
> The first step is to find uget-integrator.py file. In Windows, it should be in `C:\Program Files (x86)\uget-integrator`, unless you used the portable option.
> 
> ### Edit uget-integrator.py
> In uget-integrator.py find the line.
>
> ```
> fileName = basename(urlparse(url).path).replace('%20', ' ')
> ```
> Comment out the line and add a new line as shown below
> 
> ```
> #fileName = basename(urlparse(url).path).replace('%20', ' ')
> fileName = ""
> ```

EDIT: I want to thank myself for this tip 🤝 as I'm now on linux and had forgotten how to fix this issue. It's a similar fix except that uget-integrator is located at `/usr/bin/uget-integrator`
