### ISSUE TITLE
Download Videos (Experimental)

### ISSUE THREAD

**Issue by candrapersada** [ugetdm/uget-integrator#9]
Download Videos. name file same web page.
Mark Zuckerberg breaks his silence on Cambridge Analytica scandal - Mar. 21, 2018.mp4
no mark-zuckerberg-cambridge-analytica-post-commoney_2005656_1024x576.mp4

**Comment by slgobinath** [comment]
This name is taken from the actual filename. Renaming them to the web page name will have a problem when there are more than one videos on the same web page.

**Comment by candrapersada** [comment]
but download manager other use name web page, to Download Videos online.

**Comment by MichaelTunnell** [comment]
I agree with @slgobinathm using the name of the webpage would create conflicts if there are multiple videos being downloaded from the same page.
