### ISSUE TITLE
Not available in Opera Addons store

### ISSUE THREAD

**Issue by ktlinux** [ugetdm/uget-integrator#95]
Wanted to try the addon but it seems unavailable on Opera addons store

https://addons.opera.com/en-gb/extensions/details/uget-integration/

**Comment by ghost** [comment]
Opera supports to install chrome extensions.

**Comment by slgobinath** [comment]
I had Opera addons but looks like Opera removed it for some reason. I will take a look. Meanwhile please try the chrome extension on Opera as @azrea suggested.

Thanks

**Comment by ghost** [comment]
opera does such weird things. they have removed gnome shell integrator.

@slgobinath Don't you have time to enhance uget-integrator as [IDM](https://www.internetdownloadmanager.com/)?
https://chrome.google.com/webstore/detail/idm-integration-module/ngpampappnmepgilojfohadhhmbhlaek

i own two licenses from contribution gifts but it's not available for linux :smile: 
It's actually perfect for detect videos from any site and display toolbar in videoplayer corner to select required quality and download

I used to run windows vm when necessary to download videos from strange sites (that's something bad luck for linux)

**Comment by ktlinux** [comment]
So it is likely Opera's fault for the removal?

Edit: and if so, will it get back or I will have to rely on the Chrome addon?

**Comment by ghost** [comment]
>So it is likely Opera's fault for the removal?

It seems to me they've some strict condition according their preference even we see it as stupid when remove such extensions and that's why they may be support for add chrome extensions separately. 

>or I will have to rely on the Chrome addon?

I dont see any difference. furthermore, opera based on chromium

**Comment by ktlinux** [comment]
I see, thanks!
