### ISSUE TITLE
E: Unable to locate package uget-integrator

### ISSUE THREAD

**Issue by MaxCurl002** [ugetdm/uget-integrator#96]
Ubuntu 20.04

(I am a total newbie)
I installed uGet in my desktop. Then Firefox uGet Integration add-on.
But the add-on did not work, it says ,"unable to connect to uget-integrator".
Then I googled and found this command-

_sudo add-apt-repository ppa:uget-team/ppa
sudo apt update
sudo apt install uget-integrator_

But after running this command, i got this error. 

**E: Unable to locate package uget-integrator**

**Comment by Antorell** [comment]
I just tried and it's working for me

Executing 'apt download uget-integrator'


Get:1 http://ppa.launchpad.net/uget-team/ppa/ubuntu focal/main amd64 uget-integrator amd64 1.0.0-1 [4394 B]
Fetched 4394 B in 0s (37.1 kB/s)

**Comment by kareemkasem** [comment]
same issue on ubuntu 20.10

**Comment by AliJavanJ1** [comment]
for me too
same issue on Ubuntu 20.10

**Comment by AliJavanJ1** [comment]
when I run `sudo apt update` I get following message:
E: The repository 'http://ppa.launchpad.net/uget-team/ppa/ubuntu groovy Release' does not have a Release file.

**Comment by slgobinath** [comment]
I'm terribly sorry for not responding to this request as I was busy with some other commitments.
I just released the uget-integrator to Groovy. It should be available within an hour.

**Comment by 0xrafiKaji** [comment]
or me too
same issue on Kali linux 2023.1 . 
plz help

**Comment by naodalemu** [comment]
2025 and still I have the same issue. (Ubuntu 24.04.1 LTS, Release: 24.04)
Unable to locate package uget-integrator
