### ISSUE TITLE
uGet-integrator 2.1.3 configuration greyed out in FF XUbuntu 16.04 LTS 64bit

### ISSUE THREAD

**Issue by insomniacno1** [ugetdm/uget-integrator#99]
Hi, As the title says the only 2 things I can configure in uget-integrator is interupt downloads and minimum file size, the rest is grey out - is there a fix for this?

I like to remove .pdf and add some other file extensions, but can't at the moment.

Same problem in chrome.

Otherwise its working fine, thank you for the good work:)

![Screenshot_2020-12-09_08-09-47](https://user-images.githubusercontent.com/52598290/101557618-52472900-39f8-11eb-856c-0e6302b49577.png)

**Comment by slgobinath** [comment]
Hi, Those are some examples for you but not the actual values. As soon as you start typing in those fields, those values will disappear.
